<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <OutputType>Exe</OutputType>
    <UserSecretsId>41fcfc96-9608-4426-9cd8-181202f026a4</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="host.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </Content>
    <Content Include="local.settings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.DurableTask" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" />
    <PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" OutputItemType="Analyzer" />
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureAppConfiguration" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Common.DependencyInjection\Common.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\..\Entities\Entities.csproj" />
    <ProjectReference Include="..\..\..\Hosts.FunctionBase\Hosts.FunctionBase.csproj" />
    <ProjectReference Include="..\..\..\Repositories.Contracts\Repositories.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Repositories.GraphGroups\Repositories.GraphAzureADGroups.csproj" />
    <ProjectReference Include="..\..\..\Repositories.GraphUsers\Repositories.GraphAzureADUsers.csproj" />
    <ProjectReference Include="..\..\..\Repositories.Localization\Repositories.Localization.csproj" />
    <ProjectReference Include="..\..\..\Repositories.Logging\Repositories.Logging.csproj" />
    <ProjectReference Include="..\..\..\Repositories.Mail\Repositories.Mail.csproj" />
    <ProjectReference Include="..\Services\Services.csproj" />
    <ProjectReference Include="..\Services.Contracts\Services.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="System.Threading.ExecutionContext" Alias="ExecutionContext" />
  </ItemGroup>
</Project>