<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Hosts.AgentReader.Services</AssemblyName>
    <RootNamespace>Hosts.AgentReader.Services</RootNamespace>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Repositories.Contracts\Repositories.Contracts.csproj" />
    <ProjectReference Include="..\Services.Contracts\Services.Contracts.csproj" />
  </ItemGroup>
</Project>
