<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <AssemblyName>Hosts.AzureMaintenance</AssemblyName>
    <RootNamespace>Hosts.AzureMaintenance</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AdaptiveCards.Templating" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" VersionOverride="5.16.2" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Hosts.FunctionBase\Hosts.FunctionBase.csproj" />
    <ProjectReference Include="..\..\..\Repositories.GraphGroups\Repositories.GraphAzureADGroups.csproj" />
    <ProjectReference Include="..\..\..\Services.Notifications\Services.Notifications.csproj" />
    <ProjectReference Include="..\Services.Notifier\Services.Notifier.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
</Project>