# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
name: $(major).$(minor).$(Date:yyMM).$(Rev:r)

trigger:
- develop
- main

pool:
  vmImage: "windows-latest"

variables:
  "major": '2'
  "minor": '0'
  "BuildConfiguration": 'debug'
  "SolutionAbbreviation": 'gmm'
  disable.coverage.autogenerate: 'true'
  "buildRelease": ${{ in(variables['Build.SourceBranch'], 'refs/heads/main') }}

parameters:
  - name: buildSourceCode
    displayName: Build source code?
    type: boolean
    default: false

stages:

- template: build-tag.yml
  parameters:
    tagName: $(Build.BuildNumber)

- ${{ if or(eq( variables['Build.Reason'], 'Schedule' ), eq(parameters.buildSourceCode, true)) }}:
  - template: build-services.yml
    parameters:
      repoToCheckout: self
      checkoutPath: '$(Build.BuildNumber)'
      buildRelease: ${{variables.buildRelease}}

  - template: yaml/build-functionapps.yml
    parameters:
      dependsOn: Build_Common
      condition: succeeded('Build_Common')
      repoToCheckout: self
      checkoutPath: '$(Build.BuildNumber)'
      buildRelease: ${{variables.buildRelease}}
      functionApps:
      - function:
         name: 'NonProdService'
         coverageThreshold: 100
      - function:
         name: 'JobTrigger'
         coverageThreshold: 87
      - function:
         name: 'GraphUpdater'
         coverageThreshold: 74
      - function:
         name: 'TeamsChannelUpdater'
         coverageThreshold: 69
      - function:
         name: 'DestinationAttributesUpdater'
         coverageThreshold: 67
      - function:
         name: 'GroupMembershipObtainer'
         coverageThreshold: 89
      - function:
         name: 'SqlMembershipObtainer'
         coverageThreshold: 50
      - function:
         name: 'PlaceMembershipObtainer'
         coverageThreshold: 45
      - function:
         name: 'TeamsChannelMembershipObtainer'
         coverageThreshold: 72
      - function:
         name: 'AzureMaintenance'
         coverageThreshold: 95
      - function:
         name: 'AzureUserReader'
         coverageThreshold: 62
      - function:
         name: 'JobScheduler'
         coverageThreshold: 48
      - function:
         name: 'MembershipAggregator'
         coverageThreshold: 85
      - function:
         name: 'Notifier'
         coverageThreshold: 75
      - function:
         name: 'GroupOwnershipObtainer'
         coverageThreshold: 80

  - template: yaml/build-release-package.yml
    parameters:
      repoToCheckout: self
      checkoutPath: '$(Build.BuildNumber)'
      buildRelease: ${{variables.buildRelease}}