<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights" />
    <ProjectReference Include="..\Repositories.Contracts\Repositories.Contracts.csproj" />
  </ItemGroup>

</Project>
