<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Microsoft.ApplicationInsights" />
    <PackageReference Include="Microsoft.ApplicationInsights.WorkerService" />
    <PackageReference Include="Microsoft.AspNetCore.Localization" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Configuration.AzureAppConfiguration" />
    <PackageReference Include="Microsoft.Extensions.Localization" />
    <PackageReference Include="Microsoft.FeatureManagement" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Common.DependencyInjection\Common.DependencyInjection.csproj" />
    <ProjectReference Include="..\DIConcreteTypes\DIConcreteTypes.csproj" />
    <ProjectReference Include="..\Repositories.EntityFramework.Contexts\Repositories.EntityFramework.Contexts.csproj" />
    <ProjectReference Include="..\Repositories.EntityFramework\Repositories.EntityFramework.csproj" />
    <ProjectReference Include="..\Repositories.FeatureFlag\Repositories.FeatureFlag.csproj" />
    <ProjectReference Include="..\Repositories.Localization\Repositories.Localization.csproj" />
    <ProjectReference Include="..\Repositories.Logging\Repositories.Logging.csproj" />
    <ProjectReference Include="..\Repositories.Mail\Repositories.Mail.csproj" />
    <ProjectReference Include="..\Repositories.ServiceBusQueue\Repositories.ServiceBusQueue.csproj" />
    <ProjectReference Include="..\Repositories.RetryPolicyProvider\Repositories.RetryPolicyProvider.csproj" />
    <ProjectReference Include="..\Repositories.Contracts\Repositories.Contracts.csproj" />
  </ItemGroup>

</Project>