<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AdaptiveCards.Templating" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>
	
  <ItemGroup>
    <ProjectReference Include="..\DIConcreteTypes\DIConcreteTypes.csproj" />
    <ProjectReference Include="..\Models\Models.csproj" />
    <ProjectReference Include="..\Repositories.GraphGroups\Repositories.GraphAzureADGroups.csproj" />
    <ProjectReference Include="..\Services.Contracts\Services.Contracts.csproj" />
  </ItemGroup>

</Project>