<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
	  <PackageReference Include="Azure.Identity" Version="1.12.0" />
	  <PackageReference Include="Azure.Monitor.Query" Version="1.4.0" />
	  <PackageReference Include="Microsoft.ApplicationInsights" Version="2.22.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Repositories.Contracts\Repositories.Contracts.csproj" />
    <ProjectReference Include="..\Services.Contracts\Services.Contracts.csproj" />
    <ProjectReference Include="..\Services.Entities\Services.Entities.csproj" />
  </ItemGroup>

</Project>
