<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
	  <PackageReference Include="AdaptiveCards.Templating" />
	  <PackageReference Include="Azure.Identity" />
	  <PackageReference Include="Azure.Monitor.Query" />
	  <PackageReference Include="Microsoft.ApplicationInsights" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Repositories.Contracts\Repositories.Contracts.csproj" />
    <ProjectReference Include="..\..\..\Services.Contracts\Services.Contracts.csproj" />
    <ProjectReference Include="..\Services.Notifier.Contracts\Services.Notifier.Contracts.csproj" />
  </ItemGroup>

</Project>