<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AzureFunctionsVersion>v4</AzureFunctionsVersion>
    <AssemblyName>SqlMembershipObtainer</AssemblyName>
    <RootNamespace>SqlMembershipObtainer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="NewFolder\**" />
    <EmbeddedResource Remove="NewFolder\**" />
    <None Remove="NewFolder\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask.Analyzers" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" VersionOverride="5.16.2" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" />
    <PackageReference Include="NJsonSchema" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Activity\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Common.DependencyInjection\Common.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\..\DIConcreteTypes\DIConcreteTypes.csproj" />
    <ProjectReference Include="..\..\..\Hosts.FunctionBase\Hosts.FunctionBase.csproj" />
    <ProjectReference Include="..\..\..\Models\Models.csproj" />
    <ProjectReference Include="..\..\..\Repositories.BlobStorage\Repositories.BlobStorage.csproj" />
    <ProjectReference Include="..\..\..\Repositories.DataFactory\Repositories.DataFactory.csproj" />
    <ProjectReference Include="..\..\..\Repositories.ServiceBusQueue\Repositories.ServiceBusQueue.csproj" />
    <ProjectReference Include="..\..\..\Repositories.SqlMembershipRepository\Repositories.SqlMembershipRepository.csproj" />
    <ProjectReference Include="..\Services.Contracts\Services.Contracts.csproj" />
    <ProjectReference Include="..\Services\Services\Services.csproj" />
  </ItemGroup>
</Project>