<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ApplicationInsights" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Graph" />
    <PackageReference Include="Microsoft.Graph.Core" />
    <PackageReference Include="Polly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hosts\SqlMembershipObtainer.Common\SqlMembershipObtainer.Entities\SqlMembershipObtainer.Entities.csproj" />
    <ProjectReference Include="..\Models\Models.csproj" />
  </ItemGroup>

</Project>
