<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AdaptiveCards.Templating" Version="2.0.2" />
    <PackageReference Include="Microsoft.Graph" Version="5.56.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Repositories.Contracts\Repositories.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Templates\DefaultCard.html">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
