<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.ResourceManager.AppService" />
    <PackageReference Include="Azure.ResourceManager.Storage" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" />
    <PackageReference Include="Microsoft.ApplicationInsights" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" />
    <PackageReference Include="Microsoft.AspNetCore.OData" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Polly" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common.DependencyInjection\Common.DependencyInjection.csproj" />
    <ProjectReference Include="..\..\..\Entities\Entities.csproj" />
    <ProjectReference Include="..\..\..\Repositories.DataFactory\Repositories.DataFactory.csproj" />
    <ProjectReference Include="..\..\..\Repositories.Localization\Repositories.Localization.csproj" />
    <ProjectReference Include="..\..\..\Services.Contracts\Services.Contracts.csproj" />
    <ProjectReference Include="..\..\GraphUpdater\Services.Entities\Services.Entities.csproj" />
    <ProjectReference Include="..\Services.Messages.Contracts\Services.Messages.Contracts.csproj" />
    <ProjectReference Include="..\Services.Messages\Services.Messages.csproj" />
    <ProjectReference Include="..\Services.WebApi.Contracts\Services.WebApi.Contracts.csproj" />
    <ProjectReference Include="..\WebApi.Models\WebApi.Models.csproj" />
  </ItemGroup>

</Project>