// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

using System;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Models
{
    /// <summary>
    /// Represents a part of a membership query with its filter criteria and generated title.
    /// Used in the OpenAI integration for generating human-readable descriptions of SQL filters.
    /// </summary>
    public class Part
    {
        /// <summary>
        /// The SQL WHERE clause filter criteria for this part of the membership query.
        /// </summary>
        [JsonPropertyName("filter")]
        [Required]
        public string Filter { get; set; } = string.Empty;

        /// <summary>
        /// Unique identifier for this part of the membership query.
        /// </summary>
        [JsonPropertyName("partId")]
        [Required]
        public Guid PartId { get; set; }

        /// <summary>
        /// Human-readable title describing the filter criteria, typically generated by OpenAI.
        /// </summary>
        [JsonPropertyName("title")]
        public string? Title { get; set; }

        /// <summary>
        /// Initializes a new instance of the Part class.
        /// </summary>
        public Part()
        {
        }

        /// <summary>
        /// Initializes a new instance of the Part class with the specified values.
        /// </summary>
        /// <param name="partId">The unique identifier for this part.</param>
        /// <param name="filter">The SQL WHERE clause filter criteria.</param>
        /// <param name="title">The human-readable title (optional).</param>
        public Part(Guid partId, string filter, string? title = null)
        {
            PartId = partId;
            Filter = filter ?? throw new ArgumentNullException(nameof(filter));
            Title = title;
        }

        /// <summary>
        /// Returns a string representation of the Part for debugging purposes.
        /// </summary>
        /// <returns>A string containing the PartId and Filter information.</returns>
        public override string ToString()
        {
            return $"Part [Id: {PartId}, Filter: {Filter}, Title: {Title ?? "Not Set"}]";
        }

        /// <summary>
        /// Determines whether this Part has a valid, non-empty filter.
        /// </summary>
        /// <returns>True if the filter is not null or empty; otherwise, false.</returns>
        public bool HasValidFilter()
        {
            return !string.IsNullOrWhiteSpace(Filter);
        }

        /// <summary>
        /// Determines whether this Part has a title assigned.
        /// </summary>
        /// <returns>True if the title is not null or empty; otherwise, false.</returns>
        public bool HasTitle()
        {
            return !string.IsNullOrWhiteSpace(Title);
        }
    }
}