// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

import {
    type IStyle,
    type IStyleFunctionOrObject,
    type ITheme,
} from '@fluentui/react';
import type React from 'react';
import { ISourcePart } from '../../models/ISourcePart';
import { UserProfile } from '../../models/UserProfile';

/**
 * HR attribute info passed to Copilot (subset of SqlMembershipAttribute)
 */
export interface HrAttributeInfo {
    name: string;
    hasMapping: boolean;
    customLabel?: string;
    description?: string;
}

export interface ICopilotPanelStyles {
    root: IStyle;
    header: IStyle;
    headerTitle: IStyle;
    headerSubtitle: IStyle;
    sparkleStar1: IStyle;
    sparkleStar2: IStyle;
    chatContainer: IStyle;
    messagesContainer: IStyle;
    messageRow: IStyle;
    botMessage: IStyle;
    userMessage: IStyle;
    botAvatar: IStyle;
    messageContent: IStyle;
    suggestedPromptsContainer: IStyle;
    suggestedPromptsHeader: IStyle;
    suggestedPromptsGrid: IStyle;
    suggestedPromptButton: IStyle;
    welcomeCard: IStyle;
    welcomeStepList: IStyle;
    welcomeStep: IStyle;
    welcomeStepNumber: IStyle;
    welcomeStepText: IStyle;
    inputContainer: IStyle;
    inputField: IStyle;
    sendButton: IStyle;
    loadingIndicator: IStyle;
    acceptChangesContainer: IStyle;
    acceptChangesButton: IStyle;
    acceptChangesHint: IStyle;
    generateFilterButton: IStyle;
    inlineAcceptButton: IStyle;
}

export interface ICopilotPanelStyleProps {
    className?: string;
    theme: ITheme;
}

export interface IChatMessage {
    id: string;
    role: 'user' | 'assistant';
    content: string;
    timestamp: string; // ISO string for Redux serialization
}

export interface ISuggestedPrompt {
    id: string;
    label: string;
    prompt: string;
}

export interface ICopilotPanelProps extends React.AllHTMLAttributes<HTMLElement> {
    /**
     * Optional className to apply to the root of the component.
     */
    className?: string;
    /**
     * Call to provide customized styling that will layer on top of the variant rules.
     */
    styles?: IStyleFunctionOrObject<ICopilotPanelStyleProps, ICopilotPanelStyles>;
    /**
     * Whether the panel is open
     */
    isOpen: boolean;
    /**
     * Callback to dismiss the panel
     */
    dismissPanel: () => void;
    /**
     * Callback when source parts are generated by Copilot
     * @param sourceParts - The generated source parts
     * Each source part already carries its own org leader info (useOrgStructure, managerToAutoSelect, depthToAutoSelect).
     */
    onSourcePartsGenerated?: (sourceParts: ISourcePart[]) => void;
    /**
     * ID of the source part this Copilot session is for (used to track session per source part)
     */
    sourcePartId?: string;
    /**
     * User profile containing department, manager, etc. for personalized context
     */
    userProfile?: UserProfile | null;
    /**
     * HR attributes available for filtering
     */
    hrAttributes?: HrAttributeInfo[];
}
