// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

export type IStrings = {
  loading: string;
  refresh: string;
  continue: string;
  addOwner204Message: string;
  addOwner400Message: string;
  addOwner403Message: string;
  addOwnerErrorMessage: string;
  okButton: string;
  groupIdHeader: string;
  groupIdPlaceHolder: string;
  addOwnerButton: string;
  membershipManagement: string;
  learnMembershipManagement: string;
  maintenanceTitle: string;
  maintenanceMessage: string;
  permissionDenied: string;
  HROnboarding: {
    orgLeader: string;
    provideOrgLeader: string;
    orgLeaderPlaceHolder: string;
    orgLeaderInfo: string;
    depth: string;
    depthPlaceHolder: string;
    depthInfo: string;
    incrementButtonAriaLabel: string;
    decrementButtonAriaLabel: string;
    filter: string;
    filterPlaceHolder: string;
    filterInfo: string;
    includeOrg: string;
    includeFilter: string;
    group: string;
    ungroup: string;
    attributeTitle: string;
    addAttribute: string;
    attribute: string;
    equalityOperator: string;
    attributeValue: string;
    orAndOperator: string;
    attributeInfo: string;
    equalityOperatorInfo: string;
    equalityOperatorInfoTitle: string;
    equalToDescription: string;
    lessThanDescription: string;
    lessThanOrEqualDescription: string;
    greaterThanDescription: string;
    greaterThanOrEqualDescription: string;
    notEqualToDescription: string;
    inDescription: string;
    notInDescription: string;
    inOperatorDescription: string;
    notInOperatorDescription: string;
    notEqualToOperatorDescription: string;
    attributeValueInfo: string;
    orAndOperatorInfo: string;
    missingAttributeErrorMessage: string;
    customOrgLeaderMissingErrorMessage: string;
    orgLeaderMissingErrorMessage: string;
    source: string;
    invalidInputErrorMessage: string;
    valueComboBoxOptionCodeLabel: string;
    descriptionLabel: string;
    attributeDisabledErrorMessage: string;
    supportPlaceHolder: string;
    all: string;
    level: string;
    levelsPlural: string;
    down: string;
    up: string;
    andOrInfoTitle: string;
    andLogicDescription: string;
    orLogicDescription: string;
    AND: string;
    OR: string;
    any: string;
    allLowercase: string;
    IN: string;
    NOTIN: string;
    notEqualTo: string;
    orgLeaderTitle: string;
    orgLeaderSingleLevelTitle: string;
    orgLeaderMultipleLevelsTitle: string;
    withSummarizedCriteria: string;
    loadingText: string;
    generateTitle: string;
    generatingTitleText: string;
    multipleItemsSelected: string;
    selectionColumnAriaLabel: string;
    selectRowAriaLabel: string;
    comboBoxCaretAriaLabel: string;
  },
  Components: {
    AppHeader: {
      title: string;
      settings: string;
      reviewDisclaimer: string;
    },
    AppFooter: {
      switchToLightMode: string;
      switchToDarkMode: string;
    },
    Banner: {
      bannerMessageStart: string;
      clickHere: string;
      bannerMessageEnd: string;
      expandBanner: string;
    },
    HyperlinkSetting: {
      address: string;
      addHyperlink: string;
      invalidUrl: string;
    },
    InfoIcon: {
      ariaLabel: string;
    },
    GroupQuerySource: {
      searchGroupSuggestedText: string;
      noResultsFoundText: string;
      loadingText: string;
      selectionAriaLabel: string;
      removeButtonAriaLabel: string;
      validQuery: string;
      invalidQuery: string;
      searchGroupName: string;
    }
  },
  AdminConfig: {
    labels: {
      pageTitle: string;
      saveButton: string;
      saveSuccess: string;
    },
    Errors:{
      forbidden: string;
    },
    HyperlinkSettings: {
      labels: {
        hyperlinks: string;
        description: string;
      },
      dashboardLink: {
        title: string;
        description: string;
      },
      outlookWarningLink: {
        title: string;
        description: string;
      }
      privacyPolicyLink: {
        title: string;
        description: string;
      },
    },
    Operations: {
      labels: {
        operations: string;
        description: string;
        title: string;
      };
      buttons: {
        stop: string;
        stopping: string;
        reset: string;
        resetting: string;
        start: string;
        starting: string;
      };
    },
    CustomSourceSettings: {
      labels: {
        customSource: string;
        sourceDescription: string;
        sourceCustomLabelInput: string;
        listOfAttributes: string;
        listOfAttributesDescription: string;
        attributeColumn: string;
        customLabelColumn: string;
        customLabelInputPlaceHolder: string;
        valuesColumn: string;
        valuesDropdownSpinnerLabel: string;
        valuesDropdownPlaceholder: string;
        valuesDropdownTitle: string;
        descriptionColumn: string;
        enabledColumn: string;
        enabledToggleTitle: string;
        descriptionPlaceHolder: string;
      },
    },
    GeneralSettings: {
      labels: {
        general: string;
        reviewOwnSubmissionTitle: string;
        reviewOwnSubmissionDescription: string;
        createGroupTitle: string;
        createGroupDescription: string;
        businessJustificationTitle: string;
        businessJustificationDescription: string;
        isDisclaimerEnabledTitle: string;
        isDisclaimerEnabledDescription: string;
        isAutoApprovalForGroupBasedSyncsEnabledTitle: string;
        isAutoApprovalForGroupBasedSyncsEnabledDescription: string;
        isAutoApprovalForRequestorIsOrgLeaderSyncsEnabledTitle: string;
        isAutoApprovalForRequestorIsOrgLeaderSyncsEnabledDescription: string;
        isAITitleEnabledTitle: string;
        isAITitleEnabledDescription: string;
      }
    }
  },
  Authentication: {
    loginFailed: string;
  },
  JobDetails: {
    labels: {
      pageTitle: string;
      sectionTitle: string;
      lastModifiedby: string;
      requestedBy: string;
      requestedOnBehalfOf: string;
      groupLinks: string;
      destination: string;
      type: string;
      name: string;
      ID: string;
      teamName: string;
      channelName: string;
      channelId: string;
      configuration: string;
      startDate: string;
      endDate: string;
      lastRun: string;
      nextRun: string;
      frequency: string;
      frequencyDescription: string;
      requestor: string;
      increaseThreshold: string;
      decreaseThreshold: string;
      noThresholdSet: string;
      thresholdViolations: string;
      sourceParts: string;
      membershipStatus: string;
      hiddenMembershipWarning: string;
      sync: string;
      enabled: string;
      disabled: string;
      pendingReview: string;
      pendingReviewDescription: string;
      pendingReviewInstructions: string;
      pendingConfiguration: string;
      pendingConfigurationInstructions: string;
      businessJustification: string;
      approve: string;
      reject: string;
      submissionRejected: string;
      rejectionDialogTitle: string;
      rejectionDialogSubText: string;
      rejectionReasonLabel: string;
      rejectionReasonPlaceholder: string;
      submitRejection: string;
      submittingRejection: string;
      removeGMM: string;
      removeGMMWarning: string;
      removeGMMConfirmation: string;
    };
    descriptions: {
      requestedBy: string;
      requestedOnBehalfOf: string;
      startDate: string;
      endDate: string;
      type: string;
      id: string;
      lastRun: string;
      nextRun: string;
      frequency: string;
      requestor: string;
      increaseThreshold: string;
      decreaseThreshold: string;
      thresholdViolations: string;
    };
    MessageBar: {
      dismissButtonAriaLabel: string;
    };
    Errors:{
      jobInProgress: string;
      forbidden: string;
      internalError: string;
      removeGMMError: string;
      submitterNotOwner: string;
      reviewerCannotReviewOwnSubmission: string;
      rejectionError: string;
    };
    Panel: {
      dismissButtonAriaLabel: string;
      changeTimeColumnLabel: string;
      changedByColumnLabel: string;
      changeReasonColumnLabel: string;
      changeDetailsColumnLabel: string;
      viewDetails: string;
      history: string;
      configurationPivotHeader: string;
      syncPivotHeader: string;
      runIdColumnLabel: string;
      startTimeColumnLabel: string;
      endTimeColumnLabel: string;
      durationColumnLabel: string;
      statusColumnLabel: string;
      beforeSyncUserCountColumnLabel: string;
      usersAddedColumnLabel: string;
      usersRemovedColumnLabel: string;
      afterSyncUserCountColumnLabel: string;
      thresholdViolationsColumnLabel: string;
      updatedByFunctionColumnLabel: string;
      createdAtColumnLabel: string;
      updatedAtColumnLabel: string;
      onboardingRequest: string;
      onboardingAutoApproved: string;
      statusUpdate: string;
      update: string;
      submissionApproved: string;
      submissionRejected: string;
      ignoreThresholdOnce: string;
      businessJustification: string;
      groupSettings: string;
      takeAction: string;
      RunHistoryStatus: {
        idle: string;
        failed: string;
        thresholdExceeded: string;
        membershipDataNotFound: string;
        destinationGroupNotFound: string;
        notOwnerOfDestinationGroup: string;
        securityGroupNotFound: string;
        guestUsersNotSupported: string;
      };
      downloadAriaLabel: string;
      downloadError: string;
      downloadColumnLabel: string;
      downloadLinkText: string;
      downloadingText: string;
      statusFilterLabel: string;
      statusFilterAllOption: string;
      searchUserLabel: string;
      searchUserPlaceholder: string;
      searchUserNoResults: string;
      searchUserLoading: string;
      searchUserError: string;
      searchUserProgressUnavailableMessage: string;
      userAddedPriorToHistoryMessage: string;
      userNeverInGroupOrRemovedPriorToHistoryMessage: string;
    };
    notFound: string;
    openInAzure: string;
    openInTeams: string;
    viewDetails: string;
    editButton: string;
  };
  JobsList: {
    listOfMemberships: string;
    ShimmeredDetailsList: {
      toggleSelection: string;
      toggleAllSelection: string;
      selectRow: string;
      ariaLabelForShimmer: string;
      ariaLabelForGrid: string;
      columnNames: {
        name: string;
        type: string;
        lastRun: string;
        nextRun: string;
        lastModified: string;
        status: string;
        actionRequired: string;
        email: string;
      };
    };
    MessageBar: {
      dismissButtonAriaLabel: string;
    };
    PagingBar: {
      previousPage: string;
      nextPage: string;
      page: string;
      of: string;
      display: string;
      items: string;
      pageNumberAriaLabel: string;
      pageSizeAriaLabel: string;
    };
    JobsListFilter: {
      filters: {
        ID: {
          label: string;
          placeholder: string;
          validationErrorMessage: string;
        };
        status: {
          label: string;
          options: {
            all: string;
            enabled: string;
            disabled: string;
          };
        };
        actionRequired: {
          label: string;
          options: {
            all: string;
            thresholdExceeded: string;
            customerPaused: string;
            developerPaused: string;
            membershipDataNotFound: string;
            destinationGroupNotFound: string;
            notOwnerOfDestinationGroup: string;
            securityGroupNotFound: string;
            pendingReview: string;
            pendingConfiguration: string;
            submissionRejected: string;
            nestedGroupsFound: string;
            guestUsersCannotBeAddedToUnifiedGroup: string;
          };
        };
        destinationType: {
          label: string;
          options: {
            all: string;
            channel: string;
            group: string;
          };
        };
        destinationName: {
          label: string;
          placeholder: string;
        };
        ownerPeoplePicker: {
          label: string;
          suggestionsHeaderText:string;
          noResultsFoundText: string;
          loadingText: string;
          selectionAriaLabel: string;
          removeButtonAriaLabel: string;
        };
      };
      filterButtonText: string;
      clearButtonTooltip: string;
    };
    NoResults: string;
  };
  ManageMembership: {
    manageMembershipButton: string;
    addSyncButton: string;
    bulkAddSyncsButton: string;
    bulkApproveSyncsButton: string;
    downloadButton: string;
    downloadingButton: string;
    uploadHeader: string;
    uploadingLabel: string;
    selectCSVFileLabel: string;
    chooseFileButton: string;
    csvErrorMessage: string;
    uploadErrorMessage: string;
    uploadCompleteLabel: string;
    totalNumberOfJobsLabel: string;
    totalNumberOfApprovedJobsLabel: string;
    approveErrorStatusLabel: string;
    approveButton: string;
    labels: {
      abandonOnboarding: string;
      abandonOnboardingDescription: string;
      alreadyOnboardedWarning: string;
      confirmAbandon: string;
      pageTitle: string;
      step1title: string;
      step1description: string;
      selectOrCreateGroup: string;
      selectDestinationType: string;
      selectDestinationTypePlaceholder: string;
      selectDestination: string;
      createNewGroup: string;
      searchGroup: string;
      searchTeam: string;
      searchChannel: string;
      searchGroupSuggestedText: string;
      searchChannelSuggestedText: string;
      noResultsFound: string;
      appsUsed: string;
      entraSecurityGroup: string;
      onPremisesSyncedGroup: string;
      outlookWarning: string;
      teamsNotSupportedWarning: string;
      appIdNotOwnerWarning: string;
      addOwnerMessage: string;
      teamsServiceAccountNotOwnerWarning: string;
      userNotOwnerWarning: string;
      hasNestedGroupsWarning: string;
      nestedGroupsFound: string;
      viewInEntra: string;
      here: string;
      refreshInstructions: string;
      checkAgain: string;
      groupDescription: string;
      channelDescription: string;
      step2title: string;
      step2description: string;
      advancedQuery: string;
      advancedView: string;
      query: string;
      validQuery: string;
      invalidQuery: string;
      invalidGroups: string;
      invalidSqlFilters: string;
      step3title: string;
      step3description: string;
      selectStartDate: string;
      ASAP: string;
      requestedDate: string;
      selectRequestedStartDate: string;
      from: string;
      hrs: string;
      frequency: string;
      preventAutomaticSync: string;
      preventAutomaticSyncInfo: string;
      preventAutomaticSyncWarning: string;
      increase: string;
      decrease: string;
      step4title: string;
      step4description: string;
      objectId: string;
      sourceParts: string;
      sourcePart: string;
      hiddenMembershipGroup: string;
      noThresholdSet: string;
      savingSyncJob: string;
      updatingSyncJob: string;
      group: string;
      destinationPickerSuggestionsHeaderText: string;
      expand: string;
      collapse: string;
      sourceType: string;
      addSourcePart: string;
      includeSourcePart: string;
      yesInclusionary: string;
      noInclusionary: string;
      deleteLastSourcePartWarning: string;
      errorOnSchema: string;
      searchGroupName: string;
      HR: string;
      groupMembership: string;
      groupOwnership: string;
      placeMembership: string;
      clickHere: string;
      requestor: string;
      requestorInfo: string;
      businessJustificationSubtitle: string;
      businessJustificationPrompt: string;
      businessJustificationPlaceholder: string;
      requestedBy: string;
      requestedOnBehalfOf: string;
      requestedOnBehalfOfPlaceholder: string;
      requestedOnBehalfOfDescription: string;
      expandAll: string;
      collapseAll: string;
      allUsersInGroup: string;
      allUsersInFallback: string;
      hiddenMembershipConfirmationWarning: string;
    },
    CreateGroup: {
      createNewGroup: string;
      groupName: string;
      groupNamePlaceholder: string;
      groupAlias: string;
      groupAliasPlaceholder: string;
      creating: string;
      created: string;
      createGroup: string;
      authorizedSenders: string;
      authorizedSendersToolTip: string;
      hiddenFromExchangeClients: string
      hiddenFromExchangeClientsToolTip: string
      welcomeMessageEnabled: string;
      welcomeMessageEnabledToolTip: string;
    }
  };
  excludePrefix: string;
  copy: string;
  remove: string;
  delete: string;
  edit: string;
  submit: string;
  needHelp: string;
  next: string;
  close: string;
  cancel: string;
  learnMore: string;
  errorItemNotFound: string;
  welcome: string;
  back: string;
  backToDashboard: string;
  version: string;
  yes: string;
  no: string;
  or: string;
  and: string;
  true: string;
  false: string;
  privacyPolicy: string;
  hoursAgo: string;
  hoursLeft: string;
  pendingInitialSync: string;
  Disclaimer: {
    title: string;
    submitButton: string;
    membershipRules: string;
    membershipRulesBoldNote: string;
    outlookWelcomeMessage: string;
    autoSubscribeSettings: string;
    authorizedSenders: string;
    authorizedSendersBoldNote: string;
    teamsVivaNotifications: string;
    flatList: string;
      membersAutoFollowGroupConversationsOption: string;
      myGroupsUI: string;
  };
};
