<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Repositories.Contracts\Repositories.Contracts.csproj" />
    <ProjectReference Include="..\Services.Contracts\Services.Contracts.csproj" />
    <ProjectReference Include="..\Services.Entities\Services.Entities.csproj" />
  </ItemGroup>

</Project>