<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>SyncJobUpdater.Services.Contracts</AssemblyName>
    <RootNamespace>Services.Contracts</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Models\Models.csproj" />
  </ItemGroup>

</Project>
