parameters:
- name: solutionAbbreviation
  type: string
- name: tenantId
  type: string
- name: subscriptionId
  type: string
- name: subscriptionName
  type: string
- name: keyVaultReaders
  type: object
- name: environmentAbbreviation
  type: string
- name: location
  type: string
- name: serviceConnection
  type: string
- name: dependsOn
  type: object
- name: stageName
  type: string
- name: condition
  type: object
- name: functionApps
  type: object

stages:
  - stage: ${{ parameters.stageName }}
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}

    jobs:
    - deployment: ${{ parameters.stageName }}_DeployResources
      displayName: ${{ parameters.stageName }}_DeployResources
      pool:
        vmImage: "windows-latest"
      # creates an environment if it doesn't exist
      variables:
        ${{ if in(parameters.stageName, 'Prod_production', 'NonProd_ua') }}:
          buildType: 'release'
        ${{ if notIn(parameters.stageName, 'Prod_production', 'NonProd_ua') }}:
          buildType: 'debug'
      environment: ${{ parameters.solutionAbbreviation }}-${{ parameters.environmentAbbreviation }}
      strategy:
        runOnce:
          deploy:
           steps:
           - template: deploy-resources.yml
             parameters:
               solutionAbbreviation: ${{ parameters.solutionAbbreviation }}
               environmentAbbreviation: ${{ parameters.environmentAbbreviation }}
               serviceConnection: ${{ parameters.serviceConnection }}
               root: $(Pipeline.Workspace)/$(Build.BuildNumber)_$(buildType)
               location: ${{ parameters.location }}
               tenantId: ${{ parameters.tenantId }}
               subscriptionName: ${{ parameters.subscriptionName }}
               subscriptionId: ${{ parameters.subscriptionId }}
               keyVaultReaders: ${{ parameters.keyVaultReaders }}

    - ${{ each app in parameters.functionApps }}:
      - job: ${{ parameters.stageName }}_DeployFunction_${{ app.function.name }}
        dependsOn:
        - ${{ parameters.stageName }}_DeployResources
        - ${{ if app.function.dependsOn }}:
          - ${{ each dependency in app.function.dependsOn }}:
            - ${{ parameters.stageName }}_DeployFunction_${{ dependency }}
        variables:
          data_storageAccountName: $[ dependencies.${{ parameters.stageName }}_DeployResources.outputs['${{ parameters.stageName }}_DeployResources.dataVariables.data_storageAccountName'] ]
          ${{ if in(parameters.stageName, 'Prod_production', 'NonProd_ua') }}:
            buildType: 'release'
          ${{ if notIn(parameters.stageName, 'Prod_production', 'NonProd_ua') }}:
            buildType: 'debug'
        steps:

          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: $(Build.BuildNumber)_$(buildType)

          - template: deploy-functionapps.yml
            parameters:
              solutionAbbreviation: ${{ parameters.solutionAbbreviation }}
              environmentAbbreviation: ${{ parameters.environmentAbbreviation }}
              serviceConnection: ${{ parameters.serviceConnection }}
              location: ${{ parameters.location }}
              tenantId: ${{ parameters.tenantId }}
              subscriptionId: ${{ parameters.subscriptionId }}
              root: $(System.ArtifactsDirectory)/$(Build.BuildNumber)_$(buildType)
              name: ${{ app.function.name }}