parameters:
- name: solutionAbbreviation
  type: string
- name: tenantId
  type: string
- name: subscriptionId
  type: string
- name: keyVaultReaders
  type: object
- name: environmentAbbreviation
  type: string
- name: location
  type: string
- name: serviceConnection
  type: string
- name: dependsOn
  type: object
- name: stageName
  type: string
- name: condition
  type: object
- name: functionApps
  type: object

stages:
  - stage: ${{ parameters.stageName }}
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}

    jobs:
    - deployment: ${{ parameters.stageName }}_DeployResources
      displayName: ${{ parameters.stageName }}_DeployResources
      pool:
        vmImage: "windows-latest"
      # creates an environment if it doesn't exist
      variables:
        ${{ if in(parameters.stageName, 'Prod_production', 'NonProd_ua') }}:
          buildType: 'release'
        ${{ if notIn(parameters.stageName, 'Prod_production', 'NonProd_ua') }}:
          buildType: 'debug'
      environment: ${{ parameters.solutionAbbreviation }}-${{ parameters.environmentAbbreviation }}
      strategy:
        runOnce:
          deploy:
           steps:
           - template: deploy-resources.yml
             parameters:
               solutionAbbreviation: ${{ parameters.solutionAbbreviation }}
               environmentAbbreviation: ${{ parameters.environmentAbbreviation }}
               serviceConnection: ${{ parameters.serviceConnection }}
               root: $(Pipeline.Workspace)/$(Build.BuildNumber)_$(buildType)
               location: ${{ parameters.location }}
               tenantId: ${{ parameters.tenantId }}
               subscriptionId: ${{ parameters.subscriptionId }}
               keyVaultReaders: ${{ parameters.keyVaultReaders }}

    - job: ${{ parameters.stageName }}_DeployFunctions
      timeoutInMinutes: 120
      dependsOn: ${{ parameters.stageName }}_DeployResources
      variables:
        data_storageAccountName: $[ dependencies.DeployResources.outputs['DeployResources.dataVariables.data_storageAccountName'] ]
        ${{ if in(parameters.stageName, 'Prod_production', 'NonProd_ua') }}:
          buildType: 'release'
        ${{ if notIn(parameters.stageName, 'Prod_production', 'NonProd_ua') }}:
          buildType: 'debug'
      steps:

        - task: DownloadBuildArtifacts@0
          inputs:
            buildType: 'current'
            downloadType: 'single'
            artifactName: $(Build.BuildNumber)_$(buildType)

        - ${{ each func in parameters.functionApps }}:
          - template: deploy-functionapps.yml
            parameters:
              solutionAbbreviation: ${{ parameters.solutionAbbreviation }}
              environmentAbbreviation: ${{ parameters.environmentAbbreviation }}
              serviceConnection: ${{ parameters.serviceConnection }}
              location: ${{ parameters.location }}
              tenantId: ${{ parameters.tenantId }}
              subscriptionId: ${{ parameters.subscriptionId }}
              root: $(System.ArtifactsDirectory)/$(Build.BuildNumber)_$(buildType)
              name: ${{ func.name }}